---
title: "Raster Analysis & Geostatistics using Kriging"
date: "Week 6: 14/11/2021"
---

<style type: "text/css">
h1.title {
	font-size: 20px;
}

h4.date {
	font-size: 18px;
}

h1 {
	font-size: 18px;
}

h2 {
	font-size: 18px;
}

body{/* Normal */
	font-size: 13px;
	text-align: justify;
}

code.r{
  font-size: 10px;
}
pre {
  font-size: 12px
}
</style>

<hr style="border:2px solid gray"> </hr>

## **4.1. List of Reading Materials**

- 1. **Technical Document**: Gurpreet Singh and Biju Soman, (2020), Spatial Interpolation using Kriging in R. [**Download here**](https://www.researchgate.net/profile/Gurpreet-Singh-183/publication/343601032_Spatial_interpolation_using_kriging_in_R/data/5f3390f2a6fdcccc43c20d3a/Spatial-interpolation-using-kriging-in-R.pdf?_sg%5B0%5D=Ox9zjHFKNoFXxoGzOO3eZtonzYqvi5LKBt84IU25txIK2YxGFuYQp96-kZNzD8Xlk9SsS7fwIJ7P1Yje1MHPGg.wf5dfrrtSj4GoBLWz3_do_QVk2whGjl0tCBt-45WueLKFrcj2fkFWkBI6Szh8nuaSkhsVHN0upqxoFuV7pYTtQ.HK05pv99BTeoysDHXvW7of8BAC3S9_e0uzhhnQdEq8M9ZC-Sr7Z-ZulLLI4I3xLuE0JWgA1A96-p29-HihUc9Q&_sg%5B1%5D=YiMQs6tMalvBlWmTzIi0jKABG87VbWwU4PY6u-BDfGbolv2TzkoJbpXLDrpiD1NmGizLizQPPT5Av_ZQpl9R4R2VEcK9Qmr52p2LmRjb0peq.wf5dfrrtSj4GoBLWz3_do_QVk2whGjl0tCBt-45WueLKFrcj2fkFWkBI6Szh8nuaSkhsVHN0upqxoFuV7pYTtQ.HK05pv99BTeoysDHXvW7of8BAC3S9_e0uzhhnQdEq8M9ZC-Sr7Z-ZulLLI4I3xLuE0JWgA1A96-p29-HihUc9Q&_sg%5B2%5D=2-ry5k1TH8C1tFxue0921sdsrR5DSFxdJSrPVPt-Wz5Km4X_9ftPpwzBMdPlW1yImyGxaOJ_G2zwZwY.SVz4moyyo-kgSfqcPMIgN1mOBRUMfLQTRdJl6UoOQtXFvbAYJqUa-n1_4g7_--KhC4bGWGaVo7C8vBcx9M1YEw&_iepl=) 
- 2. **Technical Document**: Fernando Antonanzas-Torres, (2014), Geostatistics examples in R: Ordinary Kriging, Universal Kriging and Inverse Distance Weighted. [**Download here**](https://www.researchgate.net/profile/Fernando-Antonanzas/publication/268218675_Geostatistics_examples_in_R_ordinary_kriging_universal_kriging_and_inverse_distance_weighted/links/5465c8b80cf2052b509f5b9d/Geostatistics-examples-in-R-ordinary-kriging-universal-kriging-and-inverse-distance-weighted.pdf?_sg%5B0%5D=Mkjpzx1FsDKeIE3Lo1q2rqrsWq4ljtAtH-p_j-oWBVvgIOlkRhe4yfYyNtQOZz-LhMRtrjBmurZJUyMtfplPFg.s4Bw5xYEKdD2FNPvgh1VPmaE35AZ3mdAxQXxZz0ufA1Zft1uqIa4WDkCWO7H88fpGne1qR1KcpXHEEaKy94bMg.I3j_gqSSKDGjc-eV74OI8xSw7IOOnHcU4VggPGL2a9gBG9Uj_ddHoCJmFczOQkDqVxjsB_mwokLInnIZFVNKbg&_sg%5B1%5D=Dms-97W1tB3ewXQZsY77sA0wUKF-xa51dOBC605DgRbjQ1X2XPkjf5YR9-op8AMbC5hKgAzwOaSPM75_2CgZAt-FDAbpBjaTFrMSoKehf-K6.s4Bw5xYEKdD2FNPvgh1VPmaE35AZ3mdAxQXxZz0ufA1Zft1uqIa4WDkCWO7H88fpGne1qR1KcpXHEEaKy94bMg.I3j_gqSSKDGjc-eV74OI8xSw7IOOnHcU4VggPGL2a9gBG9Uj_ddHoCJmFczOQkDqVxjsB_mwokLInnIZFVNKbg&_sg%5B2%5D=KSvH3fFgAj4KplsBk1efwMm-HTXhdLTPcn_JBqO-J0qyEgbUzPNdqHj_cRJYHSSP5Y-82UHtt0xmuns.vbf9GVK0RjovGFHisDDaHgMOdhXt1gyWu0eJP_XghCtNvArd-dhZC8961ps-h79SdjYEDB9L4mnSvl8OciOj9w&_iepl=)
- 3. **Technical Document**: Adela Volfova and Martin Smejkal, (2012), Geostatistical Methods in R. [**Download here**](https://www.researchgate.net/publication/272387573_Geostatistical_Methods_in_R/fulltext/55d63b7708aec156b9a850ea/Geostatistical-Methods-in-R.pdf?_sg%5B0%5D=E5UZBMhmZTUl03YkyOT6gfvSk-S9g0IxXYiBhog_MfA9jqVOAzfTrAL3uMFSf0rrcKPuP9r3uyx6CMqQaA6bZQ.Cmagou1MIf5IxTr09yZJ-VhaHnbSDJ6y4NVO8_8-mibVZp-Gow6ZptzkVE5muRV48tnwPVS0-0k69RXQOqd_Xw.pIpgRxYsyH5s36fBIoOHiOIYoV8layFubFo7AgAin9lirZgLcebRlzWzo9omeCpcRwwfJqOs7mVjfc8QE2lrEQ&_sg%5B1%5D=0nUelBLaKscENV-KeJ8660rYfLvHCPJdr9CCdXvdDdM4mdA0kk2JxyJSwF1Ymtgv9R_9naagCOgpmWgyq9Lfmwx3x5EFDIGePxNphad637Ey.Cmagou1MIf5IxTr09yZJ-VhaHnbSDJ6y4NVO8_8-mibVZp-Gow6ZptzkVE5muRV48tnwPVS0-0k69RXQOqd_Xw.pIpgRxYsyH5s36fBIoOHiOIYoV8layFubFo7AgAin9lirZgLcebRlzWzo9omeCpcRwwfJqOs7mVjfc8QE2lrEQ&_sg%5B2%5D=QtqpO-j-RpX4hiitIj14MC5Gm1Gz1hZQSYmbLbJddRhf9DWkpUwzthLo5_11zPPhLWXWyi-9whnPTpo.41FOaAYvHKCCInPr1E1qE4k5xMCKLIRE1awT4SlB7Zvs3IJYERUdEGthq1WH5XTXdVPpt7yDbGXHCJQuoUlGmQ&_iepl=)
- 4. **Book**: Roger S. Bivand, Edzer J. Pebesma and Virgilio Gomez-Rubio, (2008), Applied Spatial Data Analysis with R, Chapter 8: Interpolation and Geostatistics, pages 191 to 235.
- 5. **Book**: Michael Dorman, (2014), Learning R for Geospatial Analysis, Chapter 8: Spatial Interpolation of Point Data, pages 241 to 279.
- 6. **Book**: Christopher D. Lloyd, (2010), Spatial Data Analysis: An Introduction for GIS Users, Chapter 9: Spatial Interpolation (Section 9.7. Ordinary Kriging), pages 140 to 150.

</br>

## **4.2. Data Sources**
1. The pollution data was obtained from the United States Environmental Protection Agency (EPA) [**Click Here**](https://aqs.epa.gov/aqsweb/airdata/download_files.html) 
2. Spatial data concerning car usage in the US was sourced from the ACS Vehicle Availability Variables project [**Click Here**](https://www.arcgis.com/home/item.html?id=9a9e43ec1603446880c50d4ed1df2207). You would need to have Online ArcGIS account to access the resources.
3. US raster data for Social Vulnerability Index 2018 and Urbanization Index (2015) were sourced from the NASA Socioeconomic Data & Applications Center (SEDAC) [**Click Here**](https://sedac.ciesin.columbia.edu). **NOTE**: Registeration required for free access to raster records

</br>

## **4.3. Homework Exercise**
Just like $SO_{2}$, Nitrogen Oxides $NO_{X}$ are toxic gases emitted from cars, coal burning and other industrial anthropogenic-related activities. What regions in the USA have higher concentrations of $NO_{X}$ exceeding the annual average of 40 ppb? Try using the methods learnt in this practical session to make such spatial prediction. The spatial records (i.e., `NOX dataset.csv`) for Nitrogen Oxide $NO_{X}$ can be download from [**Moodle**](https://moodle.ucl.ac.uk).

<hr style="border:2px solid gray"> </hr>
